/// <reference types="vite/client" />
declare module "boxicons"
declare module "markdown-it"
declare module "markdown-it-deflist"
declare module "markdown-it-footnote"
declare module "markdown-it-mark"
declare module "markdown-it-task-lists"
declare module "highlight.js"
declare module "markdown-it-sup"
declare module "markdown-it-sub"
declare module "markdown-it-container"